/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQU1UZzRvYXdXOVp1cmgwRlpaK1ZIa3hSR2p4cGJCRkd4Mll0TnF1a3hFQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicDlqdXdXZUFkcE8reUlPaDc1TTMvb1NTN1NRQlFObi91K3dSSmpFa3VpND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRQStDMXNzQ3VNNTF4dWhMQVhTUmRGSk9wU1dYaDk2TzU2eS92TkpROTNvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5dTZiQVlsaVRhbGFzSGhJNWtPa085bGZZMHIwdDhwZm5uL0UzelRwVUd3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklQRGVCaFZ3SC9XeHcxSEJqVzlTN2xTNTFrWWQyRmpEUVJOeE5mOTNCbEU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklsOURrQkdPZGZqL1hyYlBxRWd5LzlMYXo3MSs4SFRIRWdrSHM1WWNzaEU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMlA5bDV6eHdZNW4rMWNUNkFCRUFtUTNvUkVtdWlLZWFLR2p5eUs0K3drRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQVpxRnYzVkN3Qkk2YzExUnI5dWROWG9LTjFZVFo4Y1QvNnNSTnI3NWFBMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ims1MG9GUTB1ck1VcThNdExZTElFaEZsTVJ4RC8wS3BGVDJ4T1RvUXFGQUpnUS9XNVFPMEMrWndQb1BjNXJlZGcybXZjdUJMTGJyQXgxaXQ0TVpkN0FRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjIzLCJhZHZTZWNyZXRLZXkiOiI3YlUwZUkvdzMweWlHNU9pM0JROE5mRkpKcGN1YkRXeTlGcm9IdC9kcnNVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjkxOTI2MjY1MDE3NUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJGQzZDOTFENTYxRThFMTJCRkQ4NjUxQTVFMTNDRTUwNSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMxNzM2MDY2fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJSTG5GS3gxVFJnT0FEaFZ1Z2ZmY3NBIiwicGhvbmVJZCI6ImE2ODUzNTc2LTdmYTItNDcwNy05YmQ0LTg0NGE4ZTUwNDZlMSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ0aHM5aGZoa3g4SGozejA4TlBxdmR6MzRzdUk9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic05hVitNQmJ5Y1FOZHUrRjl0UW1vMXFhaG80PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjZLNlNCSjVCIiwibWUiOnsiaWQiOiI5MTkyNjI2NTAxNzU6MjFAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ09iUWs1UURFUFBqNExrR0dBTWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjVoYkJDTTJCakFOZFdUR0h0RWhzZjZ5dE1oWHlWWDdMdEt6L3ExV3lGeVk9IiwiYWNjb3VudFNpZ25hdHVyZSI6InlTSEdvcDBSeUowdVlLNjA5Ym5jcjYrdUpvcFBzOUJoRWJCeUFBT1JKS1FCSHZ4aU0xOEU0aDc5SFJKTEFrTmFPZzBsZkovSi8xY3dkVkdGbXprMkJBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJHWjU2bnZqWkhENFBLaFVjU1J3bFI2bXpqbjlmODFwd3A5TzNiK1laaFpzQ3MwZ3BuWnM1ZkNHR2JPMVlCL0hsUHRuUm9lUzJZVXdXUUR5djJBOE9CQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjkxOTI2MjY1MDE3NToyMUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJlWVd3UWpOZ1l3RFhWa3hoN1JJYkgrc3JUSVY4bFYreTdTcy82dFZzaGNtIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMxNzM2MDYzLCJteUFwcFN0YXRlS2V5SWQiOiJBQk1BQUtUZSJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'SANJU-DOKHEBAJ';
const packname = process.env.PACKNAME || 'DHOKEBAJ-SANJU';
const dev = process.env.DEV || '919728893187';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DHOKEBAH-BOT';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'true';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
